language: python
python:
    - 3.8
    - 3.7
    - 3.6
    - 3.5
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade --pre -e .[test] pytest-cov pytest-warnings codecov
script:
  - py.test --cov jupyter_protocol jupyter_protocol
after_success:
  - codecov
